version: '3.8'

services:
    app:
        build: .
        ports:
            - "8080:8080"
        environment:
            - DATABASE_URL=postgres://urlshortener:password@postgres:5432/urlshortener?sslmode=disable
            - ENVIRONMENT=development
            - BASE_URL=http://localhost:8080
            - LOG_LEVEL=debug
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped

    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: urlshortener
            POSTGRES_USER: urlshortener
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U urlshortener -d urlshortener" ]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        restart: unless-stopped

volumes:
    postgres_data:
